[package]
name = "wos-helper"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
lazy_static = "1.4.0"
tokio = { version = "1.36.0", features = ["full"] }
