name: wosh-multi-builder

on:
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-lastest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: build
        
        run: |
          cargo build --release

      - uses: actions/upload-artifact@v4.3.3
        with:
          # Artifact name
          name: wosh*
          path: target/release/
          retention-days: 1
          
  release:
    name: "prerel"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Display fetched artifacts
        run: ls -R
      - name: Emit a Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "prerel build"
          files: |
            wosh.exe
            wosh
          
          
