name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release

    - name: upload build artifact
    - uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: wosh-pre-${{ matrix.os }}
        # A file, directory or wildcard pattern that describes what to upload
        path: rel/*.zip
        # The desired behavior if no files are found using the provided path.
        retention-days: 1
          
